[package]
name = "agent_memory"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio.workspace             = true
serde.workspace             = true
serde_json.workspace        = true

async-trait.workspace       = true
qdrant-client.workspace     = true

agent_schema.workspace      = true

# agent_schema = { path = "../../crates/agent_schema", version = "*", default-features = false }